---
# The label used to mark namespaces to belong to an organization
OrganizationLabel: appuio.io/organization
# UserDefaultOrganizationAnnotation is the annotation the default organization setting for a user is stored in.
UserDefaultOrganizationAnnotation: appuio.io/default-organization

# QuotaOverrideNamespace is the namespace where the quota overrides for organizations are stored.
QuotaOverrideNamespace: appuio-cloud

# The fair use limit of memory usage per CPU core.
# It is possible to select limits by node selector labels.
MemoryPerCoreLimits:
- Limit: 4Gi
  NodeSelector:
    matchExpressions:
      - key: class
        operator: DoesNotExist

# Privileged* is a list of the given type allowed to bypass restrictions.
# Wildcards are supported (e.g. "system:serviceaccount:default:*" or "cluster-*-operator").
# ClusterRoles are only ever matched if they are bound through a ClusterRoleBinding,
# this is different from the behavior of Kyverno.
# This is done to prevent a user from wrongly configuring a low-privileged ClusterRole which users
# can then bind to themselves to bypass the restrictions.
PrivilegedGroups: []
PrivilegedUsers: []
PrivilegedClusterRoles:
  - cluster-admin

# Default node selectors to add to pods in this namespace
DefaultNamespaceNodeSelectorAnnotation: appuio.io/default-node-selector
# Default node selectors to add to pods if not set from namespace annotation
DefaultNodeSelector:
  appuio.io/node-class: plus

# A map containing the configuration for rolebindings that are created by default in each organization namespace.
# The keys are the name of default rolebindings to create and the values are the names of the clusterroles they bind to.
DefaultOrganizationClusterRoles:
  admin: admin
