apiVersion: apps/v1
kind: Deployment
metadata:
  name: appuio-cloud-agent
  namespace: appuio-cloud-agent
  labels:
    control-plane: appuio-cloud-agent
spec:
  selector:
    matchLabels:
      control-plane: appuio-cloud-agent
  replicas: 3
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: agent
      labels:
        control-plane: appuio-cloud-agent
    spec:
      containers:
      - command:
        - appuio-cloud-agent
        args:
        - --leader-elect
        - --config=/config/config.yaml
        volumeMounts:
          - mountPath: /config/config.yaml
            name: config
            subPath: config.yaml
        image: ghcr.io/appuio/appuio-cloud-agent:latest
        ports:
        - containerPort: 9443
        - containerPort: 8080
        name: agent
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
      serviceAccountName: appuio-cloud-agent
      terminationGracePeriodSeconds: 10
    volumes:
      - name: config
        configMap:
          name: appuio-cloud-agent-config
