//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUsageProfile) DeepCopyInto(out *ZoneUsageProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUsageProfile.
func (in *ZoneUsageProfile) DeepCopy() *ZoneUsageProfile {
	if in == nil {
		return nil
	}
	out := new(ZoneUsageProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneUsageProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUsageProfileList) DeepCopyInto(out *ZoneUsageProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZoneUsageProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUsageProfileList.
func (in *ZoneUsageProfileList) DeepCopy() *ZoneUsageProfileList {
	if in == nil {
		return nil
	}
	out := new(ZoneUsageProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneUsageProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUsageProfileSpec) DeepCopyInto(out *ZoneUsageProfileSpec) {
	*out = *in
	in.UpstreamSpec.DeepCopyInto(&out.UpstreamSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUsageProfileSpec.
func (in *ZoneUsageProfileSpec) DeepCopy() *ZoneUsageProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneUsageProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneUsageProfileStatus) DeepCopyInto(out *ZoneUsageProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneUsageProfileStatus.
func (in *ZoneUsageProfileStatus) DeepCopy() *ZoneUsageProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneUsageProfileStatus)
	in.DeepCopyInto(out)
	return out
}
