---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-pod-node-selector
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutate-pod-node-selector.appuio.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-namespace-quota
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validate-namespace-quota-projectrequests.appuio.io
    rules:
      - apiGroups:
          - project.openshift.io
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - projectrequests
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-namespace-quota
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validate-namespace-quota.appuio.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - namespaces
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-request-ratio
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: validate-request-ratio.appuio.io
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
        scope: Namespaced
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-service-cloudscale-lb
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validate-service-cloudscale-lb.appuio.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - services
    sideEffects: None
