
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: appuio-cloud-agent
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: appuio-cloud-agent
