apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appuio-cloud-agent:leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: appuio-cloud-agent:leader-election-role
subjects:
- kind: ServiceAccount
  name: appuio-cloud-agent
  namespace: appuio-cloud-agent
