apiVersion: cloudagent.appuio.io/v1
kind: ZoneUsageProfile
metadata:
  name: sample
spec:
  upstreamSpec:
    namespaceCount: 10
    resources:
      organization-compute:
        apiVersion: v1
        kind: ResourceQuota
        spec:
          hard:
            limits.cpu: "8"
            limits.memory: 20Gi
            pods: "45"
            requests.cpu: "4"
            requests.memory: 4Gi
          scopes:
            - NotTerminating
