---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cloud-agent
rules:
- apiGroups:
  - appuio.io
  resources:
  - usageprofiles
  - users
  verbs:
  - get
  - list
  - watch
