apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-agent
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cloud-agent
  annotations:
    kubernetes.io/service-account.name: cloud-agent
